# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hydroelectric App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hydroelectric App
  pod 'Parse'

  target 'Hydroelectric AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hydroelectric AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
